version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
              TaskDefinition: "arn:aws:ecs:us-west-2:820537372947:task-definition/demo-app:latest"
        LoadBalancerInfo:
          ContainerName: "demo-app"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
            awsvpcConfiguration:
              subnets: ["subnet-00efac43c40e9a222","subnet-029b0d7bb6bd80212"]
              securityGroups: "sg-0cb9d06458a4bc300"
              assignPublicIp: "ENABLED"
